### ISSUE TITLE
How to hide all stickerview button such as "rotate","flip","close" click on one temparary button 

### ISSUE THREAD

**Issue by Bhavesh5291** [dungntm58/RCStickerView#1]

**Comment by dungntm58** [comment]
Hi, @Bhavesh5291 
You can hide these buttons by setting isEnable of each function to false
Example:
```
self.isEnableRotate = false
self.isEnableFlip = false
self.isEnableClose = false
```
Or if you want to hide all buttons, you can set
`self. shouldShowEditingHandlers  = false`
